import csv
import os


STUDENTS_FILE = "data/students.csv"
SUBJECT_MARKS_FILE = "data/subject_marks.csv"
STUDY_HOURS_FILE = "data/study_hours.csv"
REPORTS_FOLDER = "reports"


def load_students():
    """Load student academic records."""
    if not os.path.exists(STUDENTS_FILE):
        return []

    with open(STUDENTS_FILE, "r", newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def load_subject_marks():
    """Load subject-wise marks."""
    if not os.path.exists(SUBJECT_MARKS_FILE):
        return []

    with open(
        SUBJECT_MARKS_FILE,
        "r",
        newline="",
        encoding="utf-8"
    ) as file:
        return list(csv.DictReader(file))


def load_study_hours():
    """Load study-hour records."""
    if not os.path.exists(STUDY_HOURS_FILE):
        return []

    with open(
        STUDY_HOURS_FILE,
        "r",
        newline="",
        encoding="utf-8"
    ) as file:
        return list(csv.DictReader(file))


def get_student_data(name):
    """Collect all available information for a student."""

    students = load_students()
    subject_marks = load_subject_marks()
    study_hours = load_study_hours()

    student = None

    for record in students:
        if record["Name"].strip().lower() == name.strip().lower():
            student = record
            break

    if student is None:
        return None

    subjects = []

    for record in subject_marks:
        if record["Name"].strip().lower() == name.strip().lower():
            subjects.append(
                {
                    "subject": record["Subject"],
                    "marks": float(record["Marks"])
                }
            )

    study = None

    for record in study_hours:
        if record["Name"].strip().lower() == name.strip().lower():
            study = float(record["StudyHours"])
            break

    percentage = float(student["Percentage"])

    if percentage >= 90:
        recommendation = (
            "Excellent performance. Maintain your current "
            "study routine and continue challenging yourself."
        )
    elif percentage >= 70:
        recommendation = (
            "Good performance. Continue practicing regularly "
            "and focus on reaching the excellent category."
        )
    elif percentage >= 50:
        recommendation = (
            "Average performance. Focus on weak subjects, "
            "practice regularly, and increase study consistency."
        )
    else:
        recommendation = (
            "Needs significant improvement. Focus on weak "
            "subjects and follow a consistent study schedule."
        )

    return {
        "name": student["Name"],
        "total": float(student["Total"]),
        "percentage": percentage,
        "grade": student["Grade"],
        "subjects": subjects,
        "study_hours": study,
        "recommendation": recommendation
    }


def generate_student_report(name):
    """Generate and save a text report for a student."""

    data = get_student_data(name)

    if data is None:
        return None

    os.makedirs(REPORTS_FOLDER, exist_ok=True)

    safe_name = "".join(
        character if character.isalnum() or character in "_-"
        else "_"
        for character in data["name"]
    )

    report_path = os.path.join(
        REPORTS_FOLDER,
        f"{safe_name}_report.txt"
    )

    report = []

    report.append("=" * 60)
    report.append("           STUDENT PERFORMANCE REPORT")
    report.append("=" * 60)

    report.append("")
    report.append("STUDENT INFORMATION")
    report.append("-" * 60)

    report.append(f"Name       : {data['name']}")
    report.append(f"Total Marks: {data['total']:.2f}")
    report.append(f"Percentage  : {data['percentage']:.2f}%")
    report.append(f"Grade       : {data['grade']}")

    report.append("")
    report.append("SUBJECT PERFORMANCE")
    report.append("-" * 60)

    if data["subjects"]:
        for subject in data["subjects"]:
            report.append(
                f"{subject['subject']:<20} "
                f"{subject['marks']:.2f}"
            )
    else:
        report.append("No subject-wise data available.")

    report.append("")
    report.append("LEARNING HABITS")
    report.append("-" * 60)

    if data["study_hours"] is not None:
        report.append(
            f"Average Study Hours : "
            f"{data['study_hours']:.2f} hours/day"
        )
    else:
        report.append("Study hours data not available.")

    report.append("")
    report.append("PERSONALIZED RECOMMENDATION")
    report.append("-" * 60)
    report.append(data["recommendation"])

    report.append("")
    report.append("=" * 60)
    report.append("Generated by Student Performance Analyzer")
    report.append("=" * 60)

    with open(
        report_path,
        "w",
        encoding="utf-8"
    ) as file:
        file.write("\n".join(report))

    return report_path